export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_USER: "SET_USER",
  GET_USER: "GET_USER",
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_IN_USER: "SIGN_IN_USER",
  GET_CART: "GET_CART",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART"
}